version: '3.9'

services:
  react:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./:/app
    command: yarn start --ssl --verbose
    stdin_open: true
    # tty: true